### ISSUE TITLE
Create Mock API Readme

### ISSUE THREAD

**Issue by felixrieseberg** [felixrieseberg/OxideFleet#58]
Ember Cli comes with http mock, keeping mocked apis in a `server` folder in the root. Since we're going with a jQuery implementation, we should probably leave a small hint explaining the mocked api in that folder.

**Comment by sedouard** [comment]
So I gave ember cli's http-mock a try. And I really like it since its express based and I already wrote a mock express server so it was literally a copy paste. But what I don't like is the hoops you gotta go through to run it in travis since its actually running a node server process externally to the app.

something like mockjax runs client side and intercepts http requests before they even go out, isolating everything in-proc and i really like that. But most importantly `ember test` on travis just works.

Going to put that in a readme.md inside the server folder under `server/api`

**Comment by sedouard** [comment]
Oh I see you assigned to yourself. I'll let you add it then! Thanks!
