### ISSUE TITLE
Menu Background Broken?

### ISSUE THREAD

**Issue by felixrieseberg** [felixrieseberg/OxideFleet#60]
![screen shot 2015-05-02 at 9 40 16 am](https://cloud.githubusercontent.com/assets/1426799/7439250/693fa62a-f0af-11e4-89b4-e33866bd69a3.png)

cc @tylergibson: 
 * Is the menu supposed to only extend over the text, but not the icons?
 * Is the lack of top margin intentional?

I assume we're just dealing with a rendering issue here, because it looks slightly broken - just wanted to get confirmation. Happy to fix!

**Comment by tylergibson** [comment]
Yep that is the intended behavior,  it's the first step towards a unified Modern style, so it does appear a little funky right now (but still usable)




On Fri, May 1, 2015 at 5:45 PM -0700, "Felix Rieseberg" <notifications@github.com<mailto:notifications@github.com>> wrote:


[screen shot 2015-05-02 at 9 40 16 am]<https://cloud.githubusercontent.com/assets/1426799/7439250/693fa62a-f0af-11e4-89b4-e33866bd69a3.png>

cc @tylergibson<https://github.com/tylergibson>:

  *   Is the menu supposed to only extend over the text, but not the icons?
  *   Is the lack of top margin intentional?

I assume we're just dealing with a rendering issue here, because it looks slightly broken - just wanted to get confirmation. Happy to fix!

-

**Comment by felixrieseberg** [comment]
Okay, let's fix this though - I'd like for `master` to always be presentable and I'm a bit bummed that the interaction here is broken too (navigation items leading nowhere). From a UX/UI point of view, this is currently a bit messy.

Conveniently, tedconnectedcar.azurewebsites.net does not deploy anything after 20e5414a2f, so the preview website is fine with being on the old version, but I'd like to move forward with something that's always deployable.

@tylergibson: Want me to fix it or do you have the time to take another stab at it?

![screen shot 2015-05-03 at 1 06 27 pm](https://cloud.githubusercontent.com/assets/1426799/7446685/e82ee1da-f195-11e4-8dd5-b886ad96588d.png)

**Comment by tylergibson** [comment]
I'm happy to fix




On Sun, May 3, 2015 at 1:16 PM -0700, "Felix Rieseberg" <notifications@github.com<mailto:notifications@github.com>> wrote:


Okay, let's fix this though - I'd like for master to always be presentable and I'm a bit bummed that the interaction here is broken too (navigation items leading nowhere). From a UX/UI point of view, this is currently a bit messy.

Conveniently, tedconnectedcar.azurewebsites.net does not deploy anything after 20e5414<https://github.com/felixrieseberg/OxideFleet/commit/20e5414a2f2caf67f41e4ac8ee1e12324cc7127b>, so the preview website is fine with being on the old version, but I'd like to move forward with something that's always deployable.

@tylergibson<https://github.com/tylergibson>: Want me to fix it or do you have the time to take another stab at it?

[screen shot 2015-05-03 at 1 06 27 pm]<https://cloud.githubusercontent.com/assets/1426799/7446685/e82ee1da-f195-11e4-8dd5-b886ad96588d.png>

-
